---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service }}-deployment
  labels:
    app: {{ .Values.service }}
spec:
  replicas: {{ .Values.replica_count }}
  selector:
    matchLabels:
      app: {{ .Values.service }}
  template:
    metadata:
      labels:
        app: {{ .Values.service }}
    spec:
      containers:
      - name: {{ .Values.service }}
        image: {{ .Values.image }}
        # Memory/CPU for autoscaling
        resources:
          requests:
            cpu: {{ .Values.requests_cpu }}
            memory: {{ .Values.requests_memory }}
          limits:
            cpu: {{ .Values.limits_cpu }}
            memory: {{ .Values.limits_memory }}
        ports:
        - containerPort: {{ .Values.containerport }}
