---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service }}-deployment
  labels:
    app: {{ .Values.service }}
spec:
  replicas: {{ .Values.replica_count }}
  selector:
    matchLabels:
      app: {{ .Values.service }}
  template:
    metadata:
      labels:
        app: {{ .Values.service }}
    spec:
      containers:
      - name: {{ .Values.service }}
        image: {{ .Values.image }}
        # Memory/CPU for autoscaling
        resources:
          requests:
            cpu: {{ .Values.requests_cpu }}
            memory: {{ .Values.requests_memory }}
          limits:
            cpu: {{ .Values.limits_cpu }}
            memory: {{ .Values.limits_memory }}
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap_env }}
        volumeMounts:
        - name: {{ .Values.volume_name }}
          mountPath: /local
        ports:
        - containerPort: {{ .Values.containerport }}
      volumes:
        - name: {{ .Values.volume_name }}
          configMap:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
            name: {{ .Values.service }}-{{ .Values.config_version }}
