kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service }}
spec:
  selector:
    app: {{ .Values.service }}
  ports:
  - protocol: TCP
    port: {{ .Values.exposedport }}
    targetPort: {{ .Values.containerport }}
