apiVersion: apps/v1
kind: Deployment
metadata:
  name: bastion
  namespace: default
  labels:
    app: centos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: centos
  template:
    metadata:
      labels:
        app: centos
    spec:
      containers:
      - name: bastion
        image: centos:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
        ports:
        - containerPort: 80
          protocol: TCP
